#
# shell/zlogout
# ログアウト時の後処理。
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

[[ -o INTERACTIVE && -t 2 ]] && {

SAYINGS=(
    "So long and thanks for all the fish.\n  -- Douglas Adams"
    "Good morning! And in case I don't see ya, good afternoon, good evening and goodnight.\n  --Truman Burbank"
)

echo $SAYINGS[$(($RANDOM % $#SAYINGS + 1))]

} >&2
